---
title: "Earthquake Forecasting"
subtitle: "Dissertation Project 2"
author: "Robin Lin s2435943"
date: "today"
date-format: "MMMM YYYY"
format: 
  pdf:
    code-line-numbers: true
editor: visual
highlight-style: atom-one
---

```{r setup, include = FALSE}
if(!require(tidyverse)){
    install.packages('tidyverse')
}
library(tidyverse)

if(!require(knitr)){
    install.packages('knitr')
}
library(knitr)

if(!require(kableExtra)){
    install.packages('kableExtra')
}
library(kableExtra)

knitr::opts_chunk$set(echo = TRUE)
print.all.code = FALSE
#Setting this TRUE will include all code chunks in the PDF

if(!require(INLA)){
    install.packages('remotes')
    remotes::install_github('inlabru-org/inlabru')

    install.packages(
      'INLA',
      repos = c(getOption('repos'), 
                INLA = 'https://inla.r-inla-download.org/R/testing'),
      dep = TRUE
    )

    remotes::install_github('edinburgh-seismicity-hub/ETAS.inlabru')
}

if(!require(tidyquant)){
        install.packages('tidyquant')
}
```

```{r}
suppressMessages({
    library(ETAS.inlabru)
    library(ggplot2)
    library(dplyr)
    library(magrittr)
    library(tidyquant)
})

# Increase num.threads if you have more cores on your computer
INLA::inla.setOption(num.threads = 2)

mu <- 1070. / 365
K <- 0.089
alpha <- 2.29
c <- 0.011
p <- 1.08

modelledDuration <- 10 # [days]

M0 <- 2

theta_etas <- data.frame(mu = mu, K = K, alpha = alpha, c = c, p = p)

Ht <- data.frame(ts = c(0., 1.5), magnitudes = c(6.7, 7.))

combined.M7.ETAS.cat <-
  generate_temporal_ETAS_synthetic(
    theta = theta_etas,
    beta.p = log(10),
    M0 = M0,
    T1 = 0,
    T2 = modelledDuration,
    Ht = Ht,
    format = 'df'
  )
combined.M7.ETAS.cat$ID <- seq_len(nrow(combined.M7.ETAS.cat))

ggplot(combined.M7.ETAS.cat) +
  geom_point(aes(x = ts, y = magnitudes, color = factor(gen))) +
  xlim(0, modelledDuration) +
  ggtitle('M7 plus background and ETAS')
```

```{r}
ggplot(combined.M7.ETAS.cat %>%
         mutate(generation = if_else(gen == -1, 'Initial', 'Child'))) +
  geom_point(aes(x = ts, y = magnitudes, color = generation)) +
  xlim(0, modelledDuration) +
  ggtitle('M7 plus background and ETAS')
```

```{r}
ggplot() +
  geom_point(data = combined.M7.ETAS.cat, 
             aes(x = ID, y = magnitudes), 
             color = 'red') #+
```

```{r}
geom_ma(data = combined.M7.ETAS.cat, 
        aes(x = ID, y = magnitudes), 
        ma_fun = SMA, n = 10)
```
